spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=c
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.web.resources.add-mappings=false
# mock | ssh
nto.executor.type=ssh
logging.file.name=logs/nto-app.log
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=512MB

nto.app.jwtSecret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
nto.app.jwtAccessExpirationMs=900000
nto.app.jwtRefreshExpirationMs=2592000000
nto.app.jwtIssuer=nto
nto.app.jwtRefreshCookieName=nto_refresh
nto.app.jwtCookieSameSite=None
nto.app.jwtCookieSecure=true
nto.app.jwtCookieDomain=
nto.app.jwtCookiePath=/
nto.app.cors.allowedOrigins=http://localhost:5173,https://api.nto.formatis.online,https://node-task-orchestrator.vercel.app
nto.mock.counterRaceDelayMs=10
nto.mock.executionDelayMs=2000
